<?php

return array(
	
	'list_icon_set' => ['fa-book',
						'fa-shopping-cart',
						'fa-gift',
						'fa-keyboard-o',
						'fa-institution',
						'fa-graduation-cap',
						'fa-car',
						'fa-space-shuttle',
						'fa-globe',
						'fa-heart',
						'fa-money',
						'fa-credit-card',
						'fa-calendar',
						'fa-pencil-square-o',
						'fa-tasks',
						'fa-music',
						'fa-headphones',
						'fa-cutlery',
						'fa-video-camera',
						'fa-film',
						'fa-puzzle-piece',
						'fa-leaf',
						'fa-star',
						'fa-archive',
						'fa-bug',
						'fa-recycle',
						],
	'default_icon' => 'fa-tasks',
);